 development:
  host: localhost
  database: bloccit_development

test:
  host: localhost
  database: bloccit_test

# set these environment variables on your prod server
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
        options:
          skip_version_check: true
          safe: true
